const router = require('express').Router();

router.get('/', (_, response) => {
	const menus = [{
		"id": 289,
		"idPai": null,
		"menusFilhos": [],
		"nome": "Home",
		"descricao": "Home",
		"route": "/home",
		"uri": "",
		"isMenu": true,
		"iconClass": "home",
		"posicaoMenu": 100,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 254,
		"idPai": null,
		"menusFilhos": [{
			"id": 255,
			"idPai": 254,
			"menusFilhos": [],
			"nome": "Layout Dinâmico",
			"descricao": "Configurações de Layout Dinâmicos.",
			"route": "/layouts-configurados",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 300,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 256,
			"idPai": 254,
			"menusFilhos": [],
			"nome": "Carga Manual",
			"descricao": "Executar as cargas de CT-e e NFS-e.",
			"route": "/importar-documentos",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 400,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 257,
			"idPai": 254,
			"menusFilhos": [],
			"nome": "Outras Despesas",
			"descricao": "Outras despesas.",
			"route": "/documento-complementar",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 500,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Emissão",
		"descricao": "Menu de emissão de documentos.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "print",
		"posicaoMenu": 200,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 290,
		"idPai": null,
		"menusFilhos": [{
			"id": 291,
			"idPai": 290,
			"menusFilhos": [],
			"nome": "Iniciar Homologação",
			"descricao": "Homologação de Transportadora",
			"route": "/homologacao-transportadoras",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 551,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 292,
			"idPai": 290,
			"menusFilhos": [],
			"nome": "Listagem de Homologações",
			"descricao": "Lista das transportadoras homologadas",
			"route": "/homologacao-transportadoras/cadastradas",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 552,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Homologação de Transportadora(s)",
		"descricao": "Homologação de Transportadora",
		"route": null,
		"uri": "",
		"isMenu": false,
		"iconClass": "truck",
		"posicaoMenu": 550,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 258,
		"idPai": null,
		"menusFilhos": [{
			"id": 259,
			"idPai": 258,
			"menusFilhos": [],
			"nome": "Consulta de CT-e",
			"descricao": "Consulta situaão de CT-e.",
			"route": "/consulta-cte",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 700,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 260,
			"idPai": 258,
			"menusFilhos": [],
			"nome": "Consulta de NFS-e",
			"descricao": "Consulta situaão de NFS-e.",
			"route": "/consulta-nfe",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 800,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 261,
			"idPai": 258,
			"menusFilhos": [],
			"nome": "Consulta de MDF-e",
			"descricao": "Consulta situaão de MDF-e.",
			"route": "/consulta-mdfe",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 900,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 262,
			"idPai": 258,
			"menusFilhos": [],
			"nome": "Manipulação de MDF-e",
			"descricao": "Manipulação de MDF-e.",
			"route": "/manipulacao-mdfe",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1000,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 263,
			"idPai": 258,
			"menusFilhos": [],
			"nome": "NFS-e Manual",
			"descricao": "NFS-e Manual.",
			"route": "/nfse-manual",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1100,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Documentos",
		"descricao": "Emissão de documentos.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "file-alt",
		"posicaoMenu": 600,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 264,
		"idPai": null,
		"menusFilhos": [{
			"id": 265,
			"idPai": 264,
			"menusFilhos": [],
			"nome": "CT-e",
			"descricao": "CT-es emitidos por terceiros.",
			"route": "/cte-recebidos",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1300,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 288,
			"idPai": 264,
			"menusFilhos": [],
			"nome": "NF-e",
			"descricao": "NF-es emitidos por terceiros",
			"route": "/nfe-recebidos",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1400,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "DF-e Sefaz",
		"descricao": "Menu Recebimento de documentos de CT-e de terceiro.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "file-pdf",
		"posicaoMenu": 1200,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 282,
		"idPai": null,
		"menusFilhos": [{
			"id": 283,
			"idPai": 282,
			"menusFilhos": [],
			"nome": "Cadastro Tarifa",
			"descricao": "Cadastro Tarifas.",
			"route": "/tarifas",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1451,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Tarifas",
		"descricao": "Tarifas.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "money-bill-wave",
		"posicaoMenu": 1450,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 266,
		"idPai": null,
		"menusFilhos": [{
			"id": 293,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Perfil",
			"descricao": "Cadastro de Perfil",
			"route": "/perfil",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1550,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 267,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Transportador",
			"descricao": "Cadastros de Transportador.",
			"route": "/transportador",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1600,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 268,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Trajeto",
			"descricao": "Cadastros de Trajetos.",
			"route": "/trajeto",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1700,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 269,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Usuários",
			"descricao": "Cadastros de Usuários.",
			"route": "/usuarios",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1800,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 270,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Embarcador",
			"descricao": "Cadastros de Embarcadores.",
			"route": "/embarcador",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 1900,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 271,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Grupo de Transportadora",
			"descricao": "Cadastros Grupo de Transportadoras.",
			"route": "/grupo-transportador",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2000,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 272,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Observação CT-e",
			"descricao": "Cadastros de Observação CT-e.",
			"route": "/observacao-cte",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2100,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 273,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Grupo de Empresa",
			"descricao": "Cadastros de Grupo de Empresas.",
			"route": "/grupo-empresa",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2200,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 274,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "CFOP",
			"descricao": "Cadastros CFOP.",
			"route": "/cfop",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2300,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 275,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Município",
			"descricao": "Cadastros Municípios.",
			"route": "/municipio",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2400,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 276,
			"idPai": 266,
			"menusFilhos": [],
			"nome": "Estado",
			"descricao": "Cadastros Estados.",
			"route": "/estado",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2500,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Cadastros",
		"descricao": "Menu Cadastros do sistema.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "money-check",
		"posicaoMenu": 1500,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 277,
		"idPai": null,
		"menusFilhos": [{
			"id": 278,
			"idPai": 277,
			"menusFilhos": [],
			"nome": "Manipulação Documentos",
			"descricao": "Manipulação Documentos.",
			"route": "/manipulacao-documentos",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2700,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Monitoramento",
		"descricao": "Menu Monitoramento de CT-e.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "shield-alt",
		"posicaoMenu": 2600,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 279,
		"idPai": null,
		"menusFilhos": [{
			"id": 280,
			"idPai": 279,
			"menusFilhos": [],
			"nome": "Auditoria de Ações",
			"descricao": "Auditoria de Ações",
			"route": "/auditoria",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 2900,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 281,
			"idPai": 279,
			"menusFilhos": [],
			"nome": "Requisições",
			"descricao": "Requisições.",
			"route": "/auditoria-requisicoes",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 3000,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Auditoria",
		"descricao": "Auditorias.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "search-plus",
		"posicaoMenu": 2800,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}, {
		"id": 284,
		"idPai": null,
		"menusFilhos": [{
			"id": 285,
			"idPai": 284,
			"menusFilhos": [],
			"nome": "CT-e Emitidos",
			"descricao": "CT-e Emitidos.",
			"route": "/cte-emitidos",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 3400,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}, {
			"id": 286,
			"idPai": 284,
			"menusFilhos": [],
			"nome": "Tickets CT-e",
			"descricao": "Tickets CT-e.",
			"route": "/tickets-cte",
			"uri": "",
			"isMenu": true,
			"iconClass": "",
			"posicaoMenu": 3500,
			"left": null,
			"right": null,
			"active": true,
			"childrenVisible": false
		}],
		"nome": "Mensageria",
		"descricao": "Mensageria.",
		"route": "",
		"uri": "",
		"isMenu": false,
		"iconClass": "envelope-open-text",
		"posicaoMenu": 3300,
		"left": null,
		"right": null,
		"active": true,
		"childrenVisible": false
	}];
	response.json(menus);
});

module.exports = router;